=== oxygen-dioxide/svs-index/data/singer-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SVS Index Singer Data",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "id",
            "names",
            "owners",
            "authors",
            "variants"
        ],
        "properties": {
            "id": {
                "description": "Unique hyphenated identifier for the singer (e.g., hatsune-miku).",
                "type": "string",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            },
            "names": {
                "description": "Map of language codes (ISO 639-1) to the singer's name.",
                "type": "object",
                "required": [
                    "en"
                ],
                "minProperties": 1,
                "additionalProperties": {
                    "type": "string"
                }
            },
            "owners": {
                "description": "List of owners for the singer.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "authors": {
                "description": "List of authors for the singer.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "homepage_url": {
                "description": "Official home page link for the singer.",
                "type": "string",
                "format": "uri"
            },
            "profile_image_url": {
                "description": "External link to a profile image.",
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "variants": {
                "description": "A list of different voicebank versions, models, or types for this singer.",
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "required": [
                        "id",
                        "names",
                        "file_url",
                        "download_page_url"
                    ],
                    "properties": {
                        "id": {
                            "description": "Unique ID for the specific variant (e.g., hatsune-miku-v4x).",
                            "type": "string",
                            "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
                        },
                        "names": {
                            "description": "Map of language codes to the variant's name.",
                            "type": "object",
                            "required": [
                                "en"
                            ],
                            "minProperties": 1,
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "file_url": {
                            "description": "Direct link for official software download, or null if not applicable.",
                            "type": [
                                "string",
                                "null"
                            ],
                            "format": "uri"
                        },
                        "download_page_url": {
                            "description": "Link to the file host page requiring manual user interaction for download, or null.",
                            "type": [
                                "string",
                                "null"
                            ],
                            "format": "uri"
                        },
                        "tags": {
                            "description": "List of tags associated with the variant.",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "additionalProperties": false
                }
            }
        },
        "additionalProperties": false
    }
}

=== oxygen-dioxide/svs-index/data/singers/e.json
[
  {
    "id": "enne-jeho",
    "names": {
      "en": "En'ne Jeho",
      "ja": "鉛音ジェホ"
    },
    "owners": [
      "KougaP"
    ],
    "authors": [
      "KougaP"
    ],
    "variants": [
      {
        "id": "enne-jeho-cvvc",
        "names": {
          "en": "En'ne Jeho",
          "ja": "鉛音ジェホ"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1s-MAlQjaEppw6gyY6kOxG1KadabSN56d/view?usp=drive_link",
        "tags": [
          "utau",
          "japanese",
          "cvvc"
        ]
      }
    ],
    "homepage_url": "https://headhunter4621.github.io/singers/en'ne-jeho/",
    "profile_image_url": "https://i.imgur.com/Fzn9vhe.png"
  }
]

=== oxygen-dioxide/svs-index/data/singers/a.json
[
  {
    "id": "argon-shikuon",
    "names": {
      "en": "Argon Shikuon",
      "ja": "紫空音アルゴン"
    },
    "owners": [
      "sushii-p, Team Cipstik"
    ],
    "authors": [
      "sushii-p"
    ],
    "variants": [
      {
        "id": "argon-shikuon-flare",
        "names": {
          "en": "Argon Shikuon FLARE",
          "ja": "紫空音アルゴンFLARE"
        },
        "file_url": "https://drive.google.com/file/d/1g461JC8Cd2ked-kAlxXHEVD4pUEUMBdQ/view?usp=sharing",
        "download_page_url": "https://satiresushi.wixsite.com/sushii-dump/download",
        "tags": [
          "lang:ja",
          "cvvc"
        ]
      }
    ]
  }
]

=== oxygen-dioxide/svs-index/data/singers/l.json
[
  {
    "id": "lem-shapeshifter",
    "names": {
      "en": "Lem Shapeshifter",
      "ja": "澪夢レム"
    },
    "owners": [
      "wik_wav"
    ],
    "authors": [
      "wik_wav"
    ],
    "variants": [
      {
        "id": "lem-v4-phascogale",
        "names": {
          "en": "Lem V4 Phascogale",
          "ja": "澪夢レムV4★ファスコガーレ"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/343690",
        "tags": [
          "utau",
          "cvvc",
          "ja"
        ]
      },
      {
        "id": "lem-v4-quoll",
        "names": {
          "en": "Lem V4 Quoll",
          "ja": "澪夢レムV4★フクロネコ"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/343688",
        "tags": [
          "utau",
          "cvvc",
          "ja"
        ]
      },
      {
        "id": "lem-v4-civet",
        "names": {
          "en": "Lem V4 Civet",
          "ja": "澪夢レムV4★シベット"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/342053",
        "tags": [
          "utau",
          "cvvc",
          "ja"
        ]
      },
      {
        "id": "lem-vccv-mongoose",
        "names": {
          "en": "Lem VCCV / CVVC Mongoose",
          "ja": "澪夢レムCVVC★マングース"
        },
        "file_url": null,
        "download_page_url": "https://wik-wav.neocities.org/lem_downloads",
        "tags": [
          "utau",
          "vccv",
          "cvvc",
          "en",
          "ja"
        ]
      },
      {
        "id": "lem-v3-weasel",
        "names": {
          "en": "Lem V3 weasel",
          "ja": "澪夢レムV3★イイズナ"
        },
        "file_url": null,
        "download_page_url": "https://wik-wav.neocities.org/lem_downloads",
        "tags": [
          "utau",
          "cvvc",
          "vcv",
          "ja"
        ]
      },
      {
        "id": "lem-diffsinger-marten",
        "names": {
          "en": "Lem Diffsinger Marten",
          "ja": "澪夢レムDS★テン"
        },
        "file_url": null,
        "download_page_url": "https://wik-wav.neocities.org/lem_downloads",
        "tags": [
          "diffsinger",
          "en",
          "jp",
          "pl"
        ]
      }
    ],
    "homepage_url": "https://wik-wav.neocities.org/Lem",
    "profile_image_url": "https://wik-wav.neocities.org/content/Lem_Pfp.jpg"
  }
]

=== oxygen-dioxide/svs-index/data/singers/w.json
[
  {
    "id": "wakae-sota",
    "names": {
      "en": "Wakae Sota",
      "ja": "若詠喪太"
    },
    "owners": [
      "GRAVEKIND"
    ],
    "authors": [
      "GRAVEKIND"
    ],
    "variants": [
      {
        "id": "wakae-sota-cvvc",
        "names": {
          "en": "Wakae Sota CVVC",
          "ja": "若詠喪太 CVVC"
        },
        "file_url": "https://storage-file-download-common.bowlroll.cloud/storage/eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3NjM0NTI2NTQsInB1YmxpYyI6ZmFsc2UsImJ1Y2tldCI6ImZpbGUiLCJkaXNwb3NpdGlvbiI6IkF0dGFjaG1lbnQiLCJyZXNvdXJjZS1pZCI6IjM0Mjk5OSIsInJldmlzaW9uIjoxfQ.frR41Y1EUOBk1rquN5wBbJ98y-tSmkYZiDfEItqPZubFhPNLrqN5Auc1_T-gJNWdp74wjc4wLSEa4lnyELAbwQ",
        "download_page_url": "https://bowlroll.net/file/342999",
        "tags": [
          "utau, multipitch, cvvc, ja, male, tenor"
        ]
      }
    ],
    "homepage_url": "https://bowlroll.net/file/342999",
    "profile_image_url": "https://ibb.co/QvbcLjTS"
  }
]

=== oxygen-dioxide/svs-index/data/singers/n.json
[
  {
    "id": "namae-shizeru",
    "names": {
      "en": "Namae Shizeru",
      "ja": "名前シレズ"
    },
    "owners": [
      "kuzutokaze"
    ],
    "authors": [
      "kurukuru2suuzi"
    ],
    "variants": [
      {
        "id": "namae-shizeru-basic",
        "names": {
          "en": "Namae Shizeru",
          "ja": "名前シレズ"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/130953",
        "tags": [
          "utau",
          "monopitch",
          "vcv",
          "vcv with vc's",
          "kana aliased"
        ]
      },
      {
        "id": "namae-shizeru-18-37",
        "names": {
          "en": "Namae Shizeru【18-37】",
          "ja": "名前シレズ【18-37】"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/161141",
        "tags": [
          "utau",
          "monopitch",
          "vcv",
          "vcv + b whatever that means",
          "kana aliased"
        ]
      },
      {
        "id": "namae-shizeru-16-97",
        "names": {
          "en": "Namae Shizeru【16-97】",
          "ja": "名前シレズ【16-97】"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/192066",
        "tags": [
          "utau",
          "monopitch",
          "vcv",
          "vcv + vc",
          "kana aliased"
        ]
      },
      {
        "id": "namae-shizeru-19-18",
        "names": {
          "en": "Namae Shizeru【19-18】",
          "ja": "名前シレズ【19-18】"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/220325",
        "tags": [
          "utau",
          "monopitch",
          "vcv",
          "vcv + b whatever that means",
          "kana aliased"
        ]
      },
      {
        "id": "namae-shizeru-18-45",
        "names": {
          "en": "Namae Shizeru【18-45】",
          "ja": "名前シレズ【18-45】"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/161142",
        "tags": [
          "utau",
          "multipitch",
          "cvvc",
          "kana aliased"
        ]
      }
    ],
    "homepage_url": "https://kurukuru2suuzi.wixsite.com/kuzutokaze/%E5%90%8D%E5%89%8D%E3%82%B7%E3%83%AC%E3%82%BAdl?lang=en"
  }
]

=== oxygen-dioxide/svs-index/data/singers/d.json
[
  {
    "id": "dominic-schoepfer",
    "names": {
      "en": "Dominic Schoepfer"
    },
    "owners": [
      "Adlez27"
    ],
    "authors": [
      "Adlez27"
    ],
    "variants": [
      {
        "id": "dominic-schoepfer-electric-eng",
        "names": {
          "en": "Dominic ELECTRIC ENG"
        },
        "file_url": null,
        "download_page_url": "https://klad.tubs.wtf/vb/dominic/electric-eng",
        "tags": [
          "utau",
          "english"
        ]
      }
    ],
    "homepage_url": "https://klad.tubs.wtf/vb/dominic/"
  }
]

=== oxygen-dioxide/svs-index/data/singers/o.json
[
  {
    "id": "otoyuki-shoya",
    "names": {
      "en": "Otoyuki Shoya",
      "ja": "音雪ショウヤ"
    },
    "owners": [
      "Otoyuki Shoya Project"
    ],
    "authors": [
      "dummyboi_ (phuctranz)"
    ],
    "variants": [
      {
        "id": "otoyuki-shoya-vcv",
        "names": {
          "en": "Otoyuki Shoya VCV",
          "ja": "音雪ショウヤVCV"
        },
        "file_url": "https://drive.google.com/file/d/1Yj_qzD4DjYDDMpjIy3dt-IEtPKStSsW4/view?usp=sharing",
        "download_page_url": "https://sites.google.com/view/otoyukishoya/vb/jpn-vcv?authuser=0",
        "tags": [
          "VCV"
        ]
      }
    ],
    "homepage_url": "https://sites.google.com/view/otoyukishoya/",
    "profile_image_url": "https://lh3.googleusercontent.com/sitesv/AAzXCkc2aTAz0GFQ1BWABRrFdwY95QKULdSCL1Rco8lFgPUna8uh5djmYiswxSff2fCYap2ZSnSkj_ddQCRdEpo8bEbbzQ95IFGowV6XsYxwagtyrj4lsYfpsE9_fhJmOg2Q1r6BiWOEZOcuxXc6-u1b3B3bjZvMMfEApA__gdxkMsYoNN4WENbMcKhbz4QqZTqEnTeoRVqsRSp79LWMXEV2_YYg73_BtbuSKZN0GaA=w1280"
  }
]

=== oxygen-dioxide/svs-index/data/singers/h.json
[
    {
        "id": "hatsune-miku",
        "names": {
            "en": "Hatsune Miku",
            "ja": "初音ミク",
            "zh": "初音未来"
        },
        "owners": [
            "Crypton Future Media, INC."
        ],
        "authors": [
            "Crypton Future Media, INC."
        ],
        "homepage_url": "https://piapro.net/",
        "profile_image_url": "https://piapro.net/intl/images/btn_miku.jpg",
        "variants": [
            {
                "id": "hatsune-miku-v4-chinese",
                "names": {
                    "en": "HATSUNE MIKU V4 CHINESE",
                    "ja": "初音ミク V4 CHINESE",
                    "zh": "初音未来 V4 CHINESE"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "hatsune-miku-v4x",
                "names": {
                    "en": "HATSUNE MIKU V4X",
                    "ja": "初音ミク V4X",
                    "zh": "初音未来 V4X"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "hatsune-miku-v4x-english",
                "names": {
                    "en": "HATSUNE MIKU V4X ENGLISH",
                    "ja": "初音ミク V4X ENGLISH",
                    "zh": "初音未来 V4X ENGLISH"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "hatsune-miku-v3",
                "names": {
                    "en": "HATSUNE MIKU V3",
                    "ja": "初音ミク V3",
                    "zh": "初音未来 V3"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "hatsune-miku-v3-english",
                "names": {
                    "en": "HATSUNE MIKU V3 ENGLISH",
                    "ja": "初音ミク V3 ENGLISH",
                    "zh": "初音未来 V3 ENGLISH"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "hatsune-miku-append",
                "names": {
                    "en": "HATSUNE MIKU Append",
                    "ja": "初音ミク Append",
                    "zh": "初音未来 Append"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            },
            {
                "id": "vocaloide2-hatsune-miku",
                "names": {
                    "en": "VOCALOID2 HATSUNE MIKU",
                    "ja": "VOCALOID2 初音ミク",
                    "zh": "VOCALOID2 初音未来"
                },
                "file_url": null,
                "download_page_url": null,
                "tags": [
                    "vocaloid"
                ]
            }
        ]
    }
]
