=== oxygen-dioxide/svs-index/data/singer-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SVS Index Singer Data",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "id",
            "names",
            "owners",
            "authors",
            "variants"
        ],
        "properties": {
            "id": {
                "description": "Unique hyphenated identifier for the singer (e.g., hatsune-miku).",
                "type": "string",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            },
            "names": {
                "description": "Map of language codes (ISO 639-1) to the singer's name.",
                "type": "object",
                "required": [
                    "en"
                ],
                "minProperties": 1,
                "additionalProperties": {
                    "type": "string"
                }
            },
            "owners": {
                "description": "List of owners for the singer.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "authors": {
                "description": "List of authors for the singer.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "homepage_url": {
                "description": "Official home page link for the singer.",
                "type": "string",
                "format": "uri"
            },
            "profile_image_url": {
                "description": "External link to a profile image.",
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "variants": {
                "description": "A list of different voicebank versions, models, or types for this singer.",
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "required": [
                        "id",
                        "names",
                        "file_url",
                        "download_page_url"
                    ],
                    "properties": {
                        "id": {
                            "description": "Unique ID for the specific variant (e.g., hatsune-miku-v4x).",
                            "type": "string",
                            "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
                        },
                        "names": {
                            "description": "Map of language codes to the variant's name.",
                            "type": "object",
                            "required": [
                                "en"
                            ],
                            "minProperties": 1,
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "file_url": {
                            "description": "Direct link for official software download, or null if not applicable.",
                            "type": [
                                "string",
                                "null"
                            ],
                            "format": "uri"
                        },
                        "download_page_url": {
                            "description": "Link to the file host page requiring manual user interaction for download, or null.",
                            "type": [
                                "string",
                                "null"
                            ],
                            "format": "uri"
                        },
                        "tags": {
                            "description": "List of tags associated with the variant.",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "additionalProperties": false
                }
            }
        },
        "additionalProperties": false
    }
}

=== oxygen-dioxide/svs-index/data/singers/z.json
[
  {
    "id": "zhibin",
    "names": {
      "en": "Zhibin",
      "zh": "挚彬"
    },
    "owners": [
      "赤松_Akamatsu"
    ],
    "authors": [
      "赤松_Akamatsu"
    ],
    "variants": [
      {
        "id": "zhibin-diffsinger",
        "names": {
          "en": "Zhibin DiffSinger",
          "zh": "挚彬 DiffSinger"
        },
        "download_page_url": "https://pan.quark.cn/s/254f030af8cb",
        "file_url": null,
        "tags": [
          "diffsinger",
          "zh"
        ]
      }
    ],
    "homepage_url": "https://zhibin.club/#singers",
    "profile_image_url": "https://cloud.zhibin.club/uploads/images/20250828/20250828222529b28c58125.png"
  }
]

=== oxygen-dioxide/svs-index/data/singers/u.json
[
  {
    "id": "umidaji",
    "names": {
      "en": "Umidaji",
      "ja": "海ダージ"
    },
    "owners": [
      "Team Brapa",
      "Patiu"
    ],
    "authors": [
      "Patiu"
    ],
    "variants": [
      {
        "id": "umidaji-beta",
        "names": {
          "en": "Umidaji Beta",
          "ja": "海ダージBETA"
        },
        "file_url": null,
        "download_page_url": "https://www.teambrapa.com.br/beta",
        "tags": [
          "diffsinger",
          "openutau",
          "lang:pt",
          "lang:en",
          "lang:ja",
          "lang:es",
          "female"
        ]
      }
    ],
    "homepage_url": "https://www.teambrapa.com.br/umidaji#voicebanks",
    "profile_image_url": "https://static.wixstatic.com/media/ca7bab_8c365f2038ff4f749d82a1cbd467813d~mv2.png/v1/fill/w_360,h_360,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/pic_voice_umidaji-ds.png"
  }
]

=== oxygen-dioxide/svs-index/data/singers/s.json
[
  {
    "id": "shizuma-saito",
    "names": {
      "en": "Shizuma Saito",
      "ja": "靜間彩冬"
    },
    "owners": [
      "cadlaxa"
    ],
    "authors": [
      "cadlaxa"
    ],
    "variants": [
      {
        "id": "shizuma-saito-v104",
        "names": {
          "en": "Shizuma Saito v104 (OPENUTAU BUNDLE)",
          "ja": "靜間彩冬 v104 (OPENUTAU BUNDLE)"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1v2NZ4SXjwE3LItTJ-O3Zs5pZJmIH7nN_/view?usp=drive_link",
        "tags": [
          "utau",
          "en",
          "ja",
          "fil",
          "cvvc",
          "arpasing"
        ]
      },
      {
        "id": "shizuma-saito-v103-enlite",
        "names": {
          "en": "Shizuma Saito v103 [EN LITE]",
          "ja": "靜間彩冬 v103 [EN LITE]"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1k6nnf91eJ7VnZAtkaZvsXSIGc7qsJQMP/view?usp=drive_link",
        "tags": [
          "utau",
          "en",
          "arpasing"
        ]
      },
      {
        "id": "shizuma-saito-v103-ja",
        "names": {
          "en": "Shizuma Saito v103 [JA]",
          "ja": "靜間彩冬 v103 [JA]"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/14wsBtoaru-GTyB9SxlaqS45LRirPo_mG/view?usp=drive_link",
        "tags": [
          "utau",
          "ja",
          "cvvc"
        ]
      },
      {
        "id": "shizuma-saito-v103-fil",
        "names": {
          "en": "Shizuma Saito v103 [FIL]",
          "ja": "靜間彩冬 v103 [FIL]"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1ouTy8A2pLj-ER--Tfv_mNV9W7cWEb84P/view?usp=drive_link",
        "tags": [
          "utau",
          "fil",
          "cvvc"
        ]
      }
    ],
    "homepage_url": "https://cadlaxa.github.io/Shizuma-Saito-site/",
    "profile_image_url": "https://drive.google.com/file/d/1EWji1o3GlDdQtzz7OGIB4xeiWSyeGv7Z/view?usp=drive_link"
  }
]

=== oxygen-dioxide/svs-index/data/singers/c.json
[
  {
    "id": "caseohloid",
    "names": {
      "en": "CaseOh",
      "ja": "ケース"
    },
    "owners": [
      "Near"
    ],
    "authors": [
      "CaseOh (RVC)",
      "Boss (Illustrator)",
      "Allen Void (KEI mimicing illustrator)",
      "MothyBea (Designer)"
    ],
    "variants": [
      {
        "id": "caseohloid-classinc",
        "names": {
          "en": "Classic"
        },
        "file_url": null,
        "download_page_url": "https://www.mediafire.com/file/zqqso0ogol3lt0v/CASE+(CLASSIC).zip/file",
        "tags": [
          "utau",
          "vcv",
          "multipitch",
          "caseoh"
        ]
      },
      {
        "id": "caseohloid-debut",
        "names": {
          "en": "CASE (DEBUT)"
        },
        "file_url": null,
        "download_page_url": "https://www.mediafire.com/file/2opvjwhzaagf8gb/CASE+(DEBUT).zip/file",
        "tags": [
          "utau",
          "vcv",
          "multipitch",
          "caseoh",
          "lower quality samples compared to classic"
        ]
      },
      {
        "id": "caseohloid-easy-mode",
        "names": {
          "en": "CASE (EASY MODE)"
        },
        "file_url": null,
        "download_page_url": "https://www.mediafire.com/file/ov0zn3e3i0nnskj/CASE+(EASY+MODE).zip/file",
        "tags": [
          "utau",
          "cv",
          "monopitch",
          "caseoh",
          "beginner friendly"
        ]
      },
      {
        "id": "caseohloid-native",
        "names": {
          "en": "CASE (NATIVE)"
        },
        "file_url": null,
        "download_page_url": "https://www.mediafire.com/file/d1ohsp7cl6acl9z/CASE+(NATIVE).zip/file",
        "tags": [
          "utau",
          "ARPAsing",
          "english",
          "monopitch",
          "caseoh"
        ]
      }
    ],
    "homepage_url": "https://utau.fandom.com/wiki/CASE#Etymology",
    "profile_image_url": "https://static.wikia.nocookie.net/utau/images/1/1a/CASE_DISPLAY.png/revision/latest?cb=20250309071648"
  }
]

=== oxygen-dioxide/svs-index/data/singers/t.json
[
  {
    "id": "tao-kha",
    "names": {
      "en": "Táo Kha"
    },
    "owners": [
      "aple"
    ],
    "authors": [
      "aple"
    ],
    "variants": [
      {
        "id": "kajine-ringo-lite",
        "names": {
          "en": "Kajine Ringo LITE",
          "ja": "齧音リンゴ LITE"
        },
        "file_url": null,
        "download_page_url": "https://mega.nz/file/Vkh0GRCB#vZchq1mrLX4lgNGNF1d3zYHDY9tbUPlezuiXr9nPIu8",
        "tags": [
          "utau",
          "ja",
          "cvvc"
        ]
      },
      {
        "id": "tao-kha-akane",
        "names": {
          "en": "Táo Kha Akane"
        },
        "file_url": null,
        "download_page_url": "https://bowlroll.net/file/343768",
        "tags": [
          "utau",
          "ja",
          "cvvc"
        ]
      }
    ],
    "homepage_url": "https://hatsune39.neocities.org/taokha",
    "profile_image_url": "https://i.ibb.co/M49qPpZ/Image.png"
  },
  {
    "id": "tarou-iwata",
    "names": {
      "en": "Tarou Iwata",
      "ja": "岩田太郎"
    },
    "owners": [
      "raccoonbutler"
    ],
    "authors": [
      "raccoonbutler"
    ],
    "variants": [
      {
        "id": "tarou-iwata-amalgamation",
        "names": {
          "en": "Tarou Iwata",
          "ja": "岩田太郎"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1HS1xie3kqcgOx090ncSryKqVOw1IyVsQ/view?usp=drive_link"
      },
      {
        "id": "tarou-iwata-flustered",
        "names": {
          "en": "Tarou Iwata",
          "ja": "岩田太郎"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1TfPhjkxOqmBhwvtqZbQeNkyDvro8ZyGJ/view?usp=drive_link"
      },
      {
        "id": "tarou-iwata-arpasing",
        "names": {
          "en": "Tarou Iwata",
          "ja": "岩田太郎"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1IliJoQWiD3gEC51tvypcvzYO4-hW9MDc/view?usp=drive_link"
      },
      {
        "id": "tarou-iwata-minecraft",
        "names": {
          "en": "Tarou Iwata",
          "ja": "岩田太郎"
        },
        "file_url": null,
        "download_page_url": "https://drive.google.com/file/d/1WeWocsyJD75UMCFwkQyt-p4Cm6DFZe_d/view?usp=drive_link"
      }
    ],
    "homepage_url": "http://utau.wikidot.com/utau:tarou-iwata",
    "profile_image_url": "https://i.postimg.cc/yNWQPYRy/Gq-H7qtf-Xg-AAZ7D8.jpg"
  }
]
